pipeline {
    agent any
    stages {
        stage('Deploy Docker Container on Jenkins Master') {
            steps {
                script {
                    // Pull the image that was built earlier (already present on Jenkins master)
                    sh '''
                    docker stop sample-node-app || true
                    docker rm sample-node-app || true
                    docker run -d --name sample-node-app -p 3000:3000 discoverdevops/sample-node-app:latest
                    '''
                }
            }
        }
    }
}
