pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials')  // Docker Hub credentials stored in Jenkins
    }
    stages {
        stage('Checkout Code') {
            steps {
                // Cloning the GitHub repo
                git branch: 'main', url: 'https://github.com/discover-devops/JenkinsDocker.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image using the Dockerfile in the repo
                    def app = docker.build("discoverdevops/myapp")
                }
            }
        }
        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    // Log in and push the Docker image to Docker Hub
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        def app = docker.build("discoverdevops/myapp")
                        app.push('latest') // Tag and push the image with 'latest' tag
                    }
                }
            }
        }
    }
}
